---
title: "Homework 3 - Visualization"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(dplyr)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_bw() + theme(legend.position = "bottom"))
```

#Problem 1

First, do some data cleaning by

1. Using appropriate variable names

2. Filtering the data based on the “Overall Health” topic

3. Including only responses from “Excellent” to “Poor”

4. Organizing responses as a factor taking levels ordered from “Excellent” to “Poor”

```{r}
library(p8105.datasets)

brfss = brfss_smart2010%>%
  janitor::clean_names()%>%
  filter(topic == "Overall Health", 
         response %in% c("Excellent", "Very good", "Good", "Fair", "Poor"))%>%
  mutate(response = factor(response, levels = c("Excellent", "Very good", "Good", "Fair", "Poor")))
         
```


After the data cleaning, begin some exploration:

1. In 2002, which states were observed at 7 locations?

```{r}

```

